### ISSUE TITLE
add Contribution guildlines

### ISSUE THREAD

**Issue by anamikarawat2305** [eitozx/Animu#4]
I want to create a contributing.md file . please assign me this issue under hacktoberfest 2022.

**Comment by Doraemon23** [comment]
Can be fixed by #5

**Comment by anamikarawat2305** [comment]
> Can be fixed by #5

You mean to say that the issue is assigned to someone else and it is resolved??

**Comment by Doraemon23** [comment]
> > Can be fixed by #5
> 
> You mean to say that the issue is assigned to someone else and it is resolved??

It is actually my PR I am linking to which I did to fix the mentioned issue

**Comment by anamikarawat2305** [comment]
> > > Can be fixed by #5
> > 
> > 
> > You mean to say that the issue is assigned to someone else and it is resolved??
> 
> It is actually my PR I am linking to which I did to fix the mentioned issue

ok cool !

**Comment by anamikarawat** [comment]
Close as someone else already done same

**Comment by eitozx** [comment]
@anamikarawat this issue is still open & you can work on this 🚶🏻

**Comment by anamikarawat2305** [comment]
@eitozx ok i will do it .
